### ISSUE TITLE
Download links no longer work.

### ISSUE THREAD

**Issue by Stripa18** [HaloCustomEdition/Halo-Custom-Edition-Ultimate-Deluxe-Extreme-Pro-Enhanced-Installer-Guide#2]
I can't use the download links. Onedrive sucks and it won't let me or my friends access the files. Just goes from one website to another that leads to the first one, creating a loop that ends up with a Request blocked page.

**Comment by Leeskjold** [comment]
I am not the OP but i have a similar structure for Halo CE. including last patch and QOL features. Please wait for my repo and I will provide everything!

**Comment by janikvonrotz** [comment]
@Stripa18 I migrated the files to Infomaniak KDrive and haven't updated the links. Also the README here is outdated.

@Stripa18 I would be very interested in your setup/repo.

**Comment by janikvonrotz** [comment]
@Stripa18 I added you as an org owner.

**Comment by Leeskjold** [comment]
Links are live! Marking this as also complete
