### ISSUE TITLE
OneDrive links do not work properly

### ISSUE THREAD

**Issue by pahaze** [HaloCustomEdition/Halo-Custom-Edition-Ultimate-Deluxe-Extreme-Pro-Enhanced-Installer-Guide#3]
Like the title suggests, the links do not work properly. When trying to visit them, I am prompted to login, afterwards, it redirects between the OneDrive page and login page multiple times before eventually saying that I cannot be signed in right now.

![image](https://github.com/user-attachments/assets/d3c0f0dc-649c-49a0-b990-8a28f2de4757)

Is there any other website this is on, such as Google Drive? Or a way to fix OneDrive?

**Comment by Leeskjold** [comment]
I am not the OP but i have a similar structure for Halo CE. including last patch and QOL features. Please wait for my repo and I will provide everything!

**Comment by Leeskjold** [comment]
Links are live! Marking this as resolved

**Comment by pahaze** [comment]
> Links are live! Marking this as resolved

Thank you very much!
